---
- name: Getting uwsgi...
  get_url: dest=/tmp/{{ uwsgi_version }}.tar.gz url={{ uwsgi_download_url }}
  sudo: no

- name: Unpacking uwsgi...
  command: chdir=/tmp /bin/tar xvf {{ uwsgi_version }}.tar.gz creates=/tmp/uwsgi-{{ uwsgi_version }}
  sudo: no

- name: Pushing uwsgi build configs...
  template: src=uwsgibuild.ini dest=/tmp/uwsgi-{{ uwsgi_version }}/buildconf/uwsgibuild.ini
  sudo: no

- name: Building uwsgi...
  shell: chdir=/tmp/uwsgi-{{ uwsgi_version }} python2.7 uwsgiconfig.py --build uwsgibuild
  environment: { UWSGI_PROFILE_OVERRIDE: "plugin_dir={{uwsgi_lib_dir}}" }
  sudo: no

- name: Building python2 plugins...
  shell: chdir=/tmp/uwsgi-{{ uwsgi_version }} python2 uwsgiconfig.py --plugin plugins/{{item}} uwsgibuild {{item}}2
  sudo: no
  with_items:
    - python
    - greenlet
    - gevent

- name: Building python3 plugins...
  shell: chdir=/tmp/uwsgi-{{ uwsgi_version }} python3 uwsgiconfig.py --plugin plugins/{{item}} uwsgibuild {{item}}3
  sudo: no
  with_items:
    - python
    - greenlet

- name: Building other uwsgi plugins
  shell: chdir=/tmp/uwsgi-{{ uwsgi_version }} python uwsgiconfig.py --plugin plugins/{{item}} uwsgibuild {{item}}
  sudo: no
  environment:
      UWSGICONFIG_PHPLIBDIR: /usr/lib/php5
      UWSGICONFIG_LUAPC: '{{ "lua5.1" if ansible_os_family == "Debian" else "lua" }}'
  with_items:
    - php
    - lua
    - cgi
    - cache
    - rpc
    - ugreen
    - fastrouter
    - router_uwsgi
    - router_redirect
    - router_basicauth
    - zergpool
    - router_rewrite
    - router_http
    - router_cache
    - rawrouter
    - router_static
    - router_redis
    - sslrouter
    - webdav
    - msgpack
    - transformation_chunked
    - transformation_gzip
    - transformation_offload
    - transformation_template
    - transformation_tofile
    - transformation_toupper


- name: Building other uwsgi plugins
  shell: chdir=/tmp/uwsgi-{{ uwsgi_version }} python uwsgiconfig.py --plugin plugins/{{item}} uwsgibuild {{item}}
  sudo: no
  environment:
      UWSGICONFIG_RUBYPATH: ruby
  with_items:
    - rack
    - rbthreads
    - fiber
  when: not (ansible_os_family == "RedHat" and ansible_lsb.major_release|int < 7)

- name: Making sure uwsgi plugin directory exists...
  file: state=directory path={{ uwsgi_lib_dir }} mode=0755

- name: Installing uwsgi...
  command: chdir=/tmp/uwsgi-{{ uwsgi_version }} install -s -m 0755 uwsgi /usr/local/bin/uwsgi
  notify: restart the uwsgi emperor

- name: Installing uwsgi plugins...
  shell: chdir=/tmp/uwsgi-{{ uwsgi_version }} install -s -m 0755 *.so {{ uwsgi_lib_dir }}
  notify: restart the uwsgi emperor

- name: Remove source files...
  file: dest=/tmp/uwsgi-{{ uwsgi_version }} state=absent
