---
- name: Making sure uwsgi dependencies are installed from apt...
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - libonig-dev
    - libqdbm-dev
    - libbz2-dev
    - libxml2-dev
    - libkrb5-dev
    - libpcre3-dev
    - libdb5.1-dev
    - python2.7-dev
    - python3-dev
    - python-greenlet-dev
    - ruby-dev
    - libphp5-embed
    - php5-dev
    - libcap-dev
    - liblua5.1-0-dev
    - libattr1-dev
  when: ansible_os_family == "Debian"

- name: Python3 greenlet on Debian 8.x and Ubuntu 14.x
  apt: pkg={{ item }} state=present
  with_items:
    - python3-greenlet
  when: >
      (ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int >= 14)
      or (ansible_distribution == 'Debian' and ansible_lsb.major_release|int >= 8)

- name: Making sure uwsgi dependencies are installed from yum...
  yum: name="{{ item }}" state=present
  with_items:
    - "@Development tools"
    - openssl-devel
    - libxml2-devel
    - krb5-devel
    - pcre-devel
    - libdbi-devel
    - python-devel
    - libedit-devel
    - gmp-devel
    - bzip2-devel
    - php-embedded
    - php-devel
    - lua-devel
    - libcap-devel
  when: ansible_os_family == "RedHat"

- name: RHEL/CentOS 7.x support for ruby
  yum: name="{{ item }}" state=present
  with_items:
      - ruby
      - ruby-devel
  when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int >= 7

